language: ruby
dist: bionic
rvm:
 - 2.5
install: git clone https://github.com/${TRAVIS_REPO_SLUG%%/*}/qubesos.github.io ~/qubesos.github.io
script: ~/qubesos.github.io/_utils/travis.sh
addons:
  apt:
    packages:
    - hunspell
    - pandoc
    - jq
notifications:
  email:
    recipients:
      - adw@qubes-os.org
    on_success: never
    on_failure: always
